fix podman setup

diff --git a/Gullveig/Makefile b/Gullveig/Makefile
--- a/Gullveig/Makefile
+++ b/Gullveig/Makefile
@@ -1,24 +1,26 @@
+CONTAINER_COMMAND := $(shell if [ -f "`which podman`" ]; then echo 'podman'; else echo '$(CONTAINER_COMMAND)'; fi)
+
 # some coloring
 RED = $(shell echo -e '\033[1;31m')
 GREEN = $(shell echo -e '\033[1;32m')
 YELLOW = $(shell echo -e '\033[1;33m')
 NC = $(shell echo -e '\033[0m') # No Color
 
-.PHONY: get_docker_id
-get_docker_id:
-	$(eval RUNNING_DOCKER_ID := $(shell docker ps | grep 'pantheon' | grep 'gullveig' | awk '{print $$1}'))
+.PHONY: get_container_id
+get_container_id:
+	$(eval RUNNING_CONTAINER_ID := $(shell $(CONTAINER_COMMAND) ps | grep 'pantheon' | grep 'gullveig' | awk '{print $$1}'))
 
 .PHONY: shell
-shell: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+shell: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running, can't get to shell.${NC}"; \
 	else \
-		docker exec -it $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && /bin/sh -l' ; \
+		$(CONTAINER_COMMAND) exec -it $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && /bin/sh -l' ; \
 	fi
 
 .PHONY: kill
 kill:
-	docker rmi `docker images | grep 'pantheon' | grep 'gullveig' | awk '{print $$3}'` || exit 0
+	$(CONTAINER_COMMAND) rmi `$(CONTAINER_COMMAND) images | grep 'pantheon' | grep 'gullveig' | awk '{print $$3}'` || exit 0
 
 .PHONY: enable_debug
 enable_debug:
@@ -28,28 +30,41 @@ enable_debug:
 		xdebug.client_port=9001\n" > /etc/php83/conf.d/50_xdebug.ini
 	$(shell kill -SIGUSR2 `ps ax| grep php-fpm | grep master | awk '{print $$1}'`)
 
-.PHONY: docker_enable_debug
-docker_enable_debug: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: disable_debug
+disable_debug:
+	@echo "" > /etc/php83/conf.d/50_xdebug.ini
+	$(shell kill -SIGUSR2 `ps ax | grep php-fpm | grep master | awk '{print $$1}'`)
+
+.PHONY: container_disable_debug
+container_disable_debug: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
+		echo "${RED}Gullveig container is not running, can't disable debug.${NC}"; \
+	else \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && make disable_debug'; \
+	fi
+
+.PHONY: container_enable_debug
+container_enable_debug: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running, can't enable debug.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && make enable_debug'; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && make enable_debug'; \
 	fi
 
 .PHONY: logs
-logs: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+logs: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running, can't view logs.${NC}"; \
 	else \
-		docker logs -f $(RUNNING_DOCKER_ID); \
+		$(CONTAINER_COMMAND) logs -f $(RUNNING_CONTAINER_ID); \
 	fi
 
 .PHONY: php_logs
-php_logs: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+php_logs: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running, can't view logs.${NC}"; \
 	else \
-		docker exec -it $(RUNNING_DOCKER_ID) sh -c 'tail -f /var/log/php-errors.log | grep -v xdebug' ; \
+		$(CONTAINER_COMMAND) exec -it $(RUNNING_CONTAINER_ID) sh -c 'tail -f /var/log/php-errors.log | grep -v xdebug' ; \
 	fi
 
 .PHONY: hooks
@@ -70,12 +85,12 @@ lint:
 	php vendor/bin/phpcs --config-set show_warnings 0 > /dev/null
 	php vendor/bin/phpcs --ignore=*/generated/* src www
 
-.PHONY: docker_lint
-docker_lint: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_lint
+container_lint: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make lint' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make lint' ; \
 	fi
 
 .PHONY: analyze
@@ -83,12 +98,12 @@ analyze:
 	echo "======= Gullveig: lint (php static analyzer) ======"
 	php vendor/bin/phpstan clear-result-cache && php vendor/bin/phpstan analyse -c phpstan.neon
 
-.PHONY: docker_analyze
-docker_analyze: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_analyze
+container_analyze: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make analyze' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make analyze' ; \
 	fi
 
 .PHONY: autofix
@@ -97,18 +112,18 @@ autofix:
 	php vendor/bin/phpcbf --config-set show_warnings 0 > /dev/null
 	php vendor/bin/phpcbf src www
 
-.PHONY: docker_deps
-docker_deps: get_docker_id
-		@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_deps
+container_deps: get_container_id
+		@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
   		echo "${RED}Gullveig container is not running.${NC}"; \
   	else \
-  		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make deps' ; \
+  		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make deps' ; \
   	fi
 
-.PHONY: docker_autofix
-docker_autofix: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_autofix
+container_autofix: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Gullveig container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make autofix' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Gullveig && HOME=/home/user su-exec user make autofix' ; \
 	fi
diff --git a/Mimir/Makefile b/Mimir/Makefile
--- a/Mimir/Makefile
+++ b/Mimir/Makefile
@@ -1,47 +1,49 @@
+CONTAINER_COMMAND := $(shell if [ -f "`which podman`" ]; then echo 'podman'; else echo '$(CONTAINER_COMMAND)'; fi)
+
 # some coloring
 RED = $(shell echo -e '\033[1;31m')
 GREEN = $(shell echo -e '\033[1;32m')
 YELLOW = $(shell echo -e '\033[1;33m')
 NC = $(shell echo -e '\033[0m') # No Color
 
-.PHONY: get_docker_id
-get_docker_id:
-	$(eval RUNNING_DOCKER_ID := $(shell docker ps | grep 'pantheon' | grep 'mimir' | awk '{print $$1}'))
+.PHONY: get_container_id
+get_container_id:
+	$(eval RUNNING_CONTAINER_ID := $(shell $(CONTAINER_COMMAND) ps | grep 'pantheon' | grep 'mimir' | awk '{print $$1}'))
 
 .PHONY: shell
-shell: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+shell: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't get to shell.${NC}"; \
 	else \
-		docker exec -it $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && /bin/sh -l' ; \
+		$(CONTAINER_COMMAND) exec -it $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && /bin/sh -l' ; \
 	fi
 
 .PHONY: kill
 kill:
-	docker rmi `docker images | grep 'pantheon' | grep 'mimir' | awk '{print $$3}'` || exit 0
+	$(CONTAINER_COMMAND) rmi `$(CONTAINER_COMMAND) images | grep 'pantheon' | grep 'mimir' | awk '{print $$3}'` || exit 0
 
-.PHONY: docker_migrate
-docker_migrate: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_migrate
+container_migrate: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't run migrations.${NC}"; \
 	else \
-		docker exec $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx migrate -e docker'; \
+		$(CONTAINER_COMMAND) exec $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx migrate -e docker'; \
 	fi
 
 .PHONY: logs
-logs: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+logs: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Pantheon container is not running, can't view logs.${NC}"; \
 	else \
-		docker logs -f $(RUNNING_DOCKER_ID); \
+		$(CONTAINER_COMMAND) logs -f $(RUNNING_CONTAINER_ID); \
 	fi
 
 .PHONY: php_logs
-php_logs: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+php_logs: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Pantheon container is not running, can't view logs.${NC}"; \
 	else \
-		docker exec -it $(RUNNING_DOCKER_ID) sh -c 'tail -f /var/log/php-errors.log | grep -v xdebug' ; \
+		$(CONTAINER_COMMAND) exec -it $(RUNNING_CONTAINER_ID) sh -c 'tail -f /var/log/php-errors.log | grep -v xdebug' ; \
 	fi
 
 SQLITE_FILE ?= data/db.sqlite
@@ -64,12 +66,12 @@ lint:
 	php vendor/bin/phpcs --config-set show_warnings 0 > /dev/null
 	php vendor/bin/phpcs --ignore=*/generated/*,src/TwirpServer.php src tests www
 
-.PHONY: docker_lint
-docker_lint: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_lint
+container_lint: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make lint' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make lint' ; \
 	fi
 
 .PHONY: analyze
@@ -77,24 +79,24 @@ analyze:
 	echo "======= Mimir: lint (php static analyzer) ======"
 	php vendor/bin/phpstan clear-result-cache && php vendor/bin/phpstan analyse -c phpstan.neon
 
-.PHONY: docker_analyze
-docker_analyze: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_analyze
+container_analyze: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make analyze' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make analyze' ; \
 	fi
 
 .PHONY: test
 test:
 	php bin/unit.php
 
-.PHONY: docker_test
-docker_test: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_test
+container_test: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make test' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make test' ; \
 	fi
 
 .PHONY: autofix
@@ -123,82 +125,95 @@ enable_debug:
 		xdebug.client_port=9001\n" > /etc/php83/conf.d/50_xdebug.ini
 	$(shell kill -SIGUSR2 `ps ax | grep php-fpm | grep master | awk '{print $$1}'`)
 
-.PHONY: docker_enable_debug
-docker_enable_debug: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: disable_debug
+disable_debug:
+	@echo "" > /etc/php83/conf.d/50_xdebug.ini
+	$(shell kill -SIGUSR2 `ps ax | grep php-fpm | grep master | awk '{print $$1}'`)
+
+.PHONY: container_disable_debug
+container_disable_debug: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
+		echo "${RED}Mimir container is not running, can't disable debug.${NC}"; \
+	else \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && make disable_debug'; \
+	fi
+
+.PHONY: container_enable_debug
+container_enable_debug: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't enable debug.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && make enable_debug'; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && make enable_debug'; \
 	fi
 
-.PHONY: docker_hooks
-docker_hooks: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_hooks
+container_hooks: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make hooks' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make hooks' ; \
 	fi
 
-.PHONY: docker_proto_gen
-docker_proto_gen: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_proto_gen
+container_proto_gen: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Common && HOME=/home/user su-exec user make proto_gen' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Common && HOME=/home/user su-exec user make proto_gen' ; \
 	fi
 
-.PHONY: docker_deps
-docker_deps: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_deps
+container_deps: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make deps' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make deps' ; \
 	fi
 
-.PHONY: docker_autofix
-docker_autofix: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_autofix
+container_autofix: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make autofix' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make autofix' ; \
 	fi
 
-.PHONY: docker_init_test_db
-docker_init_test_db: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_init_test_db
+container_init_test_db: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make init_test_db' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make init_test_db' ; \
 	fi
 
-.PHONY: docker_clean_test_db
-docker_clean_test_db: get_docker_id
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_clean_test_db
+container_clean_test_db: get_container_id
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make clean_test_db' ; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user make clean_test_db' ; \
 	fi
 
-.PHONY: docker_seed
-docker_seed: get_docker_id docker_migrate
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_seed
+container_seed: get_container_id container_migrate
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't run seeding.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx seed:run -e docker -s ClubEventSeeder --verbose'; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx seed:run -e docker -s ClubEventSeeder --verbose'; \
 	fi
 
-.PHONY: docker_seed_bigevent
-docker_seed_bigevent: get_docker_id docker_migrate
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_seed_bigevent
+container_seed_bigevent: get_container_id container_migrate
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't run seeding.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && SEED_REPEAT=20 HOME=/home/user su-exec user bin/phinx seed:run -e docker -s ClubEventSeeder --verbose'; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && SEED_REPEAT=20 HOME=/home/user su-exec user bin/phinx seed:run -e docker -s ClubEventSeeder --verbose'; \
 	fi
 
-.PHONY: docker_seed_tournament
-docker_seed_tournament: get_docker_id docker_migrate
-	@if [ "$(RUNNING_DOCKER_ID)" = "" ]; then \
+.PHONY: container_seed_tournament
+container_seed_tournament: get_container_id container_migrate
+	@if [ "$(RUNNING_CONTAINER_ID)" = "" ]; then \
 		echo "${RED}Mimir container is not running, can't run seeding.${NC}"; \
 	else \
-		docker exec -t $(RUNNING_DOCKER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx seed:run -e docker -s TournamentSeeder --verbose'; \
+		$(CONTAINER_COMMAND) exec -t $(RUNNING_CONTAINER_ID) sh -c 'cd /var/www/html/Mimir && HOME=/home/user su-exec user bin/phinx seed:run -e docker -s TournamentSeeder --verbose'; \
 	fi
